### ISSUE TITLE
Licence unspecified ?

### ISSUE THREAD

**Issue by rzr** [GENIVI/genivi-dev-platform#4]
Please add a COPYING file at root thx

As a suggestion  pick Apache-2.0 to align other layers (meta-oic) or any compatibles ones listed in spdx.org

Thanks

**Comment by gunnarx** [comment]
+1
There isn't all that much here except submodules for layers and a few conf files.
What little I contributed originally to this repo originally feel free to license it using Apache-2, MPLv2 or MIT-style.

I prefer the name LICENSE which I think is clearer.  COPYING is primarily a GNU convention isn't it?  

Anyway, for what it's worthy poky uses "LICENSE", meta-openembedded uses "COPYING.MIT"...

**Comment by gunnarx** [comment]
By the way, MIT is the most common for meta-layers isn't it?

**Comment by jeremiah** [comment]
My anecdotal data says yes, MIT is quite common. We use it in meta-ivi for example.

**Comment by gmacario** [comment]
Since I found my name in https://github.com/GENIVI/genivi-dev-platform/graphs/contributors, I herebelow state my preference for the MIT license.

If other contributors come up with a different choice, please feel free to revert my commits :stuck_out_tongue_winking_eye:

**Comment by rzr** [comment]
so MIT might be more appropriate and It's libre so we're fine

**Comment by tom--pollard** [comment]
MIT is fine for me
